version: '3.7'

services:
  
  traefik:
    image: traefik:latest
    container_name: traefik
    restart: always
    expose:
      - "8082"
    ports:
      - "443:443"
      - "127.0.0.1:8080:8080"
    command:
      - "--api=true"
      - "--api.insecure=true"
      - "--api.dashboard=true"
      - "--log.level=DEBUG"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--providers.file.filename=/dynamic_config.yml"
      - "--entrypoints.websecure.address=:443"
      - "--entryPoints.metrics.address=:8082"
      - "--metrics.prometheus.entryPoint=metrics"
      - "--certificatesresolvers.myresolver.acme.tlschallenge=true"
      # TESTING
      # - "--certificatesresolvers.myresolver.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory"
      - "--certificatesresolvers.myresolver.acme.email=$MAIL"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
    volumes:
      - "./traefik/letsencrypt:/letsencrypt"
      - "./traefik/config/dynamic_config.yml:/dynamic_config.yml"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    labels:
      - "traefik.enable=true"

  dshackle:
    image: emeraldpay/dshackle:0.13.1
    ports: 
      - "127.0.0.1:12448:12448"
      - "127.0.0.1:8545:8545"
    volumes: 
      - "./dshackle.yaml:/etc/dshackle/dshackle.yaml"
      - "./private-key-test.pem:/private-key-test.pem"
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.dshackle.loadbalancer.server.scheme=h2c"
      - "traefik.http.services.dshackle.loadbalancer.server.port=12448"
      - "traefik.http.routers.dshackle.entrypoints=websecure"
      - "traefik.http.routers.dshackle.tls.certresolver=myresolver"
      - "traefik.http.routers.dshackle.rule=Host(`$DOMAIN`) && PathPrefix(`/`)"
